### ISSUE TITLE
device not listed in esphome

### ISSUE THREAD

**Issue by flyingtech** [KaufHA/PLF12#21]
I had to restore my home assistant server.  The restore point was before getting the new plugs (4 days ago).  now I'm having issues with kauf plugs. 

the two devices did not show up in ESPhome to be adopted. but they are showing up as new devices to be integrated.  I integrated the first with no problems, but the other is asking me for an encryption key.
![image](https://github.com/KaufHA/PLF12/assets/14594149/40deb507-6b82-47db-849b-21c5d9649fa8)

But neither device is showing up in the esphome ad-on.

I'm lost??????

**Comment by bkaufx** [comment]
What you would do to manually add into the dashboard is create a yaml file and paste the following code in. Then:

- change IP address to IP address of device.
- change name and friendly_name as desired.
- after you flash once, remove use_address line

```
substitutions:
  name: kauf-plug
  friendly_name: Kauf Plug

packages:
  kauf.plf12: github://KaufHA/PLF12/kauf-plf12.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  use_address: 192.168.1.12

```
