### ISSUE TITLE
PFL12 Red/Blue Flash - offline now

### ISSUE THREAD

**Issue by PDXUser** [KaufHA/PLF12#9]
This is my ESPhome YAML file for this plug:
```

---
substitutions:
  name: dishwasher
  friendly_name: Dishwasher
  disable_entities: "false"
packages:
  Kauf.PLF12: github://KaufHA/PLF12/kauf-plf12.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
wifi:
  ssid: wifi_ssid
  password: wifi_password
  
# Optional manual IP
  manual_ip:
    static_ip: 192.168.1.209
    gateway: 192.168.1.254
    subnet: 255.255.255.0
```

I had changed the names and wanted to disable entities then add the manual IP.  It seemed to flash okay, but now not online anymore.  I checked the light and it is alternating between red/blue.  Is there a hard reset which I can do to factory reset by holding the power button down?  I tried this and it only turned off red flashing or turning on and doing the same thing red/blue - I can't find it in the phone's SSID list now.
